### ISSUE TITLE
Scope of this repository?

### ISSUE THREAD

**Issue by llrs** [DavisVaughan/extrachecks#14]
With usethis new release this repository is linked when using `use_releases_issue`. Is this just for Rstudio or it is open to other's contributions? 
There's also a collection of issues or other checks on [ThinkR](https://github.com/ThinkR-open/prepare-for-cran)

**Comment by DavisVaughan** [comment]
In the readme i have:

> If you come across an ad-hoc check that isn’t on this list, please feel free to open an issue describing it, or submit a PR!

I'm very happy to review PRs with additional checks!

This is less about advice for how to submit to CRAN, and more about what you are likely to be rejected for

**Comment by llrs** [comment]
Great, if I find some more I'll send them.
