### ISSUE TITLE
Checking data for non-ASCII characters

### ISSUE THREAD

**Issue by k5cents** [DavisVaughan/extrachecks#15]
Came across [this check](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/metro-00check.html) for a package I recently submitted. Didn't cause a rejection, just produced a NOTE I hadn't seen from [r-hub](https://builder.r-hub.io/status/metro_0.9.1.tar.gz-c7dc145bc2ee49cf9656fb7ef256404f) or `devtools::check()`. 

Only came up on the Fedora checks, which seemed to flag an en dash (E2 80 93) in my documentation.

```
checking data for non-ASCII characters ... NOTE
  Note: found 1 marked UTF-8 string
```

I whipped up this function to read the text files in a package and check for non-ASCII characters. Based off `tools::showNonASCIIfile()` but returning a data frame of lines by file.

``` r
check_non_ascii <- function() {
  purrr::map_df(
    .id = "file",
    # list common text files
    .x = fs::dir_ls(
      recurse = TRUE,
      type = "file",
      # ignore images, compressed
      regexp = "\\.(png|ico|rda)$",
      invert = TRUE
    ),
    .f = function(path) {
      x <- readLines(path, warn = FALSE)
      # from tools::showNonASCII()
      asc <- iconv(x, "latin1", "ASCII")
      ind <- is.na(asc) | asc != x
      # make data frame
      if (any(ind)) {
        tibble::tibble(
          row = which(ind),
          line = iconv(x[ind], "latin1", "ASCII", sub = "byte")
        )
      } else {
        tibble::tibble()
      }
    }
  )
}
```

```
# A tibble: 2 x 3
  file                  row line                                                                                        
  <chr>               <int> <chr>                                                                                       
1 R/data.R               64 "#'   \\item{LineDescription}{Denotes the route variant's grouping <e2><80><93> lines are a"
2 man/metro_routes.Rd    13 "\\item{LineDescription}{Denotes the route variant's grouping <e2><80><93> lines are a"   
```

**Comment by DavisVaughan** [comment]
For the most part, we just ignore these since CRAN doesn't care about them. Since it doesn't cause CRAN to reject your package, I'm going to close this one, but I like the helper!
