### ISSUE TITLE
Create anchors for checks so they can be linked accurately

### ISSUE THREAD

**Issue by nanxstats** [DavisVaughan/extrachecks#28]
First off, thanks for documenting these extra checks!

It might be useful to create a heading element for each check so they have linkable anchors. This helps people link individual checks accurately, which benefits linking precise references in code reviews and building code linters.

It is technically possible to have [headers under collapsible sections](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections) on GitHub, if you favor the existing document structure. Alternatively, the checks can be put in separate Markdown files.

As a relevant example, The VS Code extension [markdownlint](https://github.com/DavidAnson/markdownlint) used to put the linting rules in a single Markdown file under anchored headings, then [transitioned](https://github.com/DavidAnson/markdownlint/commit/13b43407475380926a8b3962c4e03a6ccfeea099) to the separate file approach as the rule size grows. In the editor, the identified linting issues have an accurate ID and the associated link to the rule, shown in the screenshot below.

<img width="709" alt="zzz" src="https://user-images.githubusercontent.com/199363/231839178-d6c0f0d2-59b2-4444-8c43-0d04b287282d.png">

**Comment by DavisVaughan** [comment]
https://github.com/DavisVaughan/extrachecks/commit/a37e1ee87e47e99ba0ed88a4dfe417141ca5d89e
