### ISSUE TITLE
submission failed for http URL

### ISSUE THREAD

**Issue by pnovack-gottshall** [DavisVaughan/extrachecks#9]
On June 12, 2020, I had a CRAN submission failed for following reason:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Found the following (possibly) invalid file URIs:
    URI: paleobiodb.org/
      From: man/KWTraits.Rd
    URI: http://www.ben.edu/faculty/pnovack-gottshall/2007_Novack-Gottshall_Ecospace.pdf
      From: man/KWTraits.Rd

Please use fully specified URLs starting with the protocol, e.g. https://....

Please fix and resubmit.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Seems they're flagging URLs that use http:// instead of https:// and flagging URLs that silence the https://

When I replaced first link with https://paleobiodb.org and changed http:// to https:// in second link, everything passed.

Ought to be a simple check to add.

**Comment by DavisVaughan** [comment]
Thanks for reporting!
